spring:
  datasource:
    url: jdbc:postgresql://ingsis-permission-db:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update