services:
  db:
    image: postgres:alpine
    container_name: ingsis-user-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5003:5432'
    volumes:
      - db-data-ingsis-user:/var/lib/postgresql/data
volumes:
  db-data-ingsis-user: